# Generated by Django 3.1.7 on 2021-03-20 05:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('body', models.TextField(blank=True, max_length=300, null=True)),
                ('summary', models.CharField(blank=True, max_length=60, null=True)),
                ('category', models.CharField(blank=True, choices=[('Politics', 'Politics'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Science', 'Science')], max_length=30, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='content/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
